### PR TITLE
New operations to determine current date on the back-end

### PR DESCRIPTION
**Pull request by edrisse**

### CODE REVIEW

**Comment by edrisse** [comment]
[Let back-end determine creation date](https://trello.com/c/ZCKAhOtb/66-let-back-end-determine-creation-date)

**Comment by Guimino** [comment]
ok

**Comment by Guimino** [comment]
@edrisse , I realized that when a visit is created the date_stopped is defined to next day, this is not the behavior used by the api for visit's creation. The Api defines the date_stopped to the same day and sets time (hours/minutes/seconds) to  23:59:59.0

**Comment by Guimino** [comment]
And I noticed that the system is allowing to create more than one visit in the same day for given patient

**Comment by edrisse** [comment]
Please test again @Guimino

**Comment by Guimino** [comment]
Merged #11

**Pull request merged**
